from __future__ import annotations

import argparse
from typing import Any


def build_parser(*, handlers: dict[str, Any]) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="PM project orchestration utilities for project workspaces")
    parser.add_argument("--config", default="")
    sub = parser.add_subparsers(dest="command", required=True)

    auth_link = sub.add_parser("auth-link")
    auth_link.add_argument("--scopes", default="")
    auth_link.add_argument("--mode", default="app-scope", choices=["app-scope", "user-oauth"])
    auth_link.add_argument("--token-type", default="user", choices=["user", "tenant"])
    auth_link.set_defaults(func=handlers["auth_link"])

    permission_bundle = sub.add_parser("permission-bundle")
    permission_bundle.add_argument("--preset", action="append", default=[])
    permission_bundle.add_argument("--scope", action="append", default=[])
    permission_bundle.add_argument("--token-type", default="tenant", choices=["user", "tenant"])
    permission_bundle.add_argument("--list-presets", action="store_true", default=False)
    permission_bundle.set_defaults(func=handlers["permission_bundle"])

    auth = sub.add_parser("auth")
    auth.add_argument("--no-group-open-reply", action="store_true", default=False)
    auth.add_argument("--no-attachment-oauth", action="store_true", default=False)
    auth.set_defaults(func=handlers["auth"])

    init = sub.add_parser(
        "init",
        help="Bind or create PM resources for a project",
        description=(
            "Initialize PM resources for a repo. By default only --project-name is needed; "
            "tasklist/doc names default to that same project name. If same-name resources are ambiguous, "
            "provide --tasklist-guid or --doc-folder-token explicitly."
        ),
    )
    init.add_argument("--repo-root", default="")
    init.add_argument("--project-name", default="", help="Primary human-readable project name; defaults to repo name")
    init.add_argument("--tasklist-guid", default="", help="Bind an existing Feishu tasklist by GUID when name matches are ambiguous")
    init.add_argument("--agent", default="")
    init.add_argument("--timeout", type=int, default=0)
    init.add_argument("--thinking", default="")
    init.add_argument("--session-key", default="")
    init.add_argument("--skip-bootstrap-task", action="store_true", default=False)
    init.add_argument("--skip-auto-run", action="store_true", default=False)
    init.add_argument("--write-config", action="store_true", default=False)
    init.add_argument("--english-name", default="", help="Optional ASCII name used for workspace/agent slug generation; required when --project-name contains non-ASCII characters")
    init.add_argument("--agent-id", default="", help="Optional explicit agent id override for workspace bootstrap")
    init.add_argument("--group-id", default="", help="Optional Feishu group id; when provided, workspace bootstrap preview/execution is also enabled")
    init.add_argument("--workspace-root", default="")
    init.add_argument("--openclaw-config", default="")
    init.add_argument("--channel", default="feishu")
    init.add_argument("--doc-folder-token", default="", help="Bind an existing Feishu docs folder by token when name matches are ambiguous")
    init.add_argument("--task-backend", default="", choices=["", "feishu", "local"])
    init.add_argument("--doc-backend", default="", choices=["", "feishu", "repo"])
    init.add_argument("--task-prefix", default="T")
    init.add_argument("--default-worker", default="codex")
    init.add_argument("--reviewer-worker", default="reviewer")
    init.add_argument("--skill", action="append", default=[])
    init.add_argument("--allow-agent", action="append", default=[])
    init.add_argument("--model-primary", default="")
    init.add_argument("--no-auth-bundle", action="store_true", default=False)
    init.add_argument("--force", action="store_true", default=False)
    init.add_argument("--replace-binding", action="store_true", default=False)
    init.add_argument("--dry-run", action="store_true", default=False)
    init.add_argument("--tasklist-name", default="", help=argparse.SUPPRESS)
    init.add_argument("--doc-folder-name", default="", help=argparse.SUPPRESS)
    init.set_defaults(func=handlers["init"])

    workspace_init = sub.add_parser(
        "workspace-init",
        help="Deprecated alias of init",
        description="Deprecated alias of `init`. Prefer `init`; tasklist/doc names default to --project-name and ambiguity should be resolved via guid/token.",
    )
    workspace_init.add_argument("--project-name", required=True, help="Primary human-readable project name")
    workspace_init.add_argument("--english-name", default="", help="Optional ASCII name used for workspace/agent slug generation; required when --project-name contains non-ASCII characters")
    workspace_init.add_argument("--agent-id", default="", help="Optional explicit agent id override for workspace bootstrap")
    workspace_init.add_argument("--group-id", required=True, help="Feishu group id for workspace bootstrap")
    workspace_init.add_argument("--repo-root", required=True)
    workspace_init.add_argument("--workspace-root", default="")
    workspace_init.add_argument("--openclaw-config", default="")
    workspace_init.add_argument("--channel", default="feishu")
    workspace_init.add_argument("--tasklist-guid", default="", help="Bind an existing Feishu tasklist by GUID when name matches are ambiguous")
    workspace_init.add_argument("--agent", default="")
    workspace_init.add_argument("--timeout", type=int, default=0)
    workspace_init.add_argument("--thinking", default="")
    workspace_init.add_argument("--session-key", default="")
    workspace_init.add_argument("--skip-bootstrap-task", action="store_true", default=False)
    workspace_init.add_argument("--skip-auto-run", action="store_true", default=False)
    workspace_init.add_argument("--write-config", action="store_true", default=False)
    workspace_init.add_argument("--doc-folder-token", default="", help="Bind an existing Feishu docs folder by token when name matches are ambiguous")
    workspace_init.add_argument("--task-backend", default="", choices=["", "feishu", "local"])
    workspace_init.add_argument("--doc-backend", default="", choices=["", "feishu", "repo"])
    workspace_init.add_argument("--task-prefix", default="T")
    workspace_init.add_argument("--default-worker", default="codex")
    workspace_init.add_argument("--reviewer-worker", default="reviewer")
    workspace_init.add_argument("--skill", action="append", default=[])
    workspace_init.add_argument("--allow-agent", action="append", default=[])
    workspace_init.add_argument("--model-primary", default="")
    workspace_init.add_argument("--no-auth-bundle", action="store_true", default=False)
    workspace_init.add_argument("--force", action="store_true", default=False)
    workspace_init.add_argument("--replace-binding", action="store_true", default=False)
    workspace_init.add_argument("--dry-run", action="store_true", default=False)
    workspace_init.add_argument("--tasklist-name", default="", help=argparse.SUPPRESS)
    workspace_init.add_argument("--doc-folder-name", default="", help=argparse.SUPPRESS)
    workspace_init.set_defaults(func=handlers["init"], _deprecated_command="workspace-init")

    sync_gsd_docs = sub.add_parser("sync-gsd-docs")
    sync_gsd_docs.add_argument("--repo-root", default="")
    sync_gsd_docs.add_argument(
        "--include",
        action="append",
        default=[],
        choices=["project", "requirements", "roadmap", "state"],
    )
    sync_gsd_docs.set_defaults(func=handlers["sync_gsd_docs"])

    sync_gsd_progress = sub.add_parser("sync-gsd-progress")
    sync_gsd_progress.add_argument("--repo-root", default="")
    sync_gsd_progress.add_argument("--phase", default="")
    sync_gsd_progress.add_argument("--task-id", default="")
    sync_gsd_progress.add_argument("--task-guid", default="")
    sync_gsd_progress.add_argument("--include-completed", action="store_true", default=False)
    sync_gsd_progress.add_argument("--no-state-append", action="store_true", default=False)
    sync_gsd_progress.set_defaults(func=handlers["sync_gsd_progress"])

    materialize_gsd_tasks = sub.add_parser("materialize-gsd-tasks")
    materialize_gsd_tasks.add_argument("--repo-root", default="")
    materialize_gsd_tasks.add_argument("--phase", default="")
    materialize_gsd_tasks.set_defaults(func=handlers["materialize_gsd_tasks"])

    route_gsd = sub.add_parser("route-gsd")
    route_gsd.add_argument("--repo-root", default="")
    route_gsd.add_argument("--phase", default="")
    route_gsd.set_defaults(func=handlers["route_gsd"])

    plan_phase = sub.add_parser("plan-phase")
    plan_phase.add_argument("--repo-root", default="")
    plan_phase.add_argument("--phase", default="")
    plan_phase.add_argument("--task-id", default="")
    plan_phase.add_argument("--task-guid", default="")
    plan_phase.add_argument("--include-completed", action="store_true", default=False)
    plan_phase.add_argument("--agent", default="")
    plan_phase.add_argument("--timeout", type=int, default=0)
    plan_phase.add_argument("--thinking", default="")
    plan_phase.add_argument("--prd", default="")
    plan_phase.add_argument("--research", action="store_true", default=False)
    plan_phase.add_argument("--skip-research", action="store_true", default=False)
    plan_phase.add_argument("--gaps", action="store_true", default=False)
    plan_phase.add_argument("--skip-verify", action="store_true", default=False)
    plan_phase.add_argument("--reviews", action="store_true", default=False)
    plan_phase.add_argument("--no-doc-sync", action="store_true", default=False)
    plan_phase.add_argument("--no-progress-sync", action="store_true", default=False)
    plan_phase.add_argument("--no-state-append", action="store_true", default=False)
    plan_phase.set_defaults(func=handlers["plan_phase"])

    context = sub.add_parser("context")
    context.add_argument("--task-id", default="")
    context.add_argument("--task-guid", default="")
    context.add_argument("--refresh", action="store_true", default=False)
    context.set_defaults(func=handlers["context"])

    nxt = sub.add_parser("next")
    nxt.add_argument("--refresh", action="store_true", default=False)
    nxt.set_defaults(func=handlers["next"])

    plan = sub.add_parser("plan")
    plan.add_argument("--task-id", default="")
    plan.add_argument("--task-guid", default="")
    plan.add_argument("--focus", default="")
    plan.set_defaults(func=handlers["plan"])

    refine = sub.add_parser("refine")
    refine.add_argument("--task-id", default="")
    refine.add_argument("--task-guid", default="")
    refine.add_argument("--focus", default="")
    refine.set_defaults(func=handlers["refine"])

    coder_context = sub.add_parser("coder-context")
    coder_context.add_argument("--task-id", default="")
    coder_context.add_argument("--task-guid", default="")
    coder_context.set_defaults(func=handlers["coder_context"])

    run = sub.add_parser("run")
    run.add_argument("--task-id", default="")
    run.add_argument("--task-guid", default="")
    run.add_argument("--backend", default="")
    run.add_argument("--agent", default="")
    run.add_argument("--timeout", type=int, default=0)
    run.add_argument("--thinking", default="")
    run.add_argument("--session-key", default="")
    run.set_defaults(func=handlers["run"])

    run_reviewed = sub.add_parser("run-reviewed")
    run_reviewed.add_argument("--task-id", default="")
    run_reviewed.add_argument("--task-guid", default="")
    run_reviewed.add_argument("--backend", default="")
    run_reviewed.add_argument("--agent", default="")
    run_reviewed.add_argument("--timeout", type=int, default=0)
    run_reviewed.add_argument("--thinking", default="")
    run_reviewed.add_argument("--session-key", default="")
    run_reviewed.set_defaults(func=handlers["run_reviewed"])

    review = sub.add_parser("review")
    review.add_argument("--task-id", default="")
    review.add_argument("--task-guid", default="")
    review.add_argument("--run-id", default="")
    review.add_argument("--verdict", required=True, choices=["pass", "fail"])
    review.add_argument("--feedback", default="")
    review.add_argument("--feedback-file", default="")
    review.add_argument("--reviewer", default="")
    review.set_defaults(func=handlers["review"])

    rerun = sub.add_parser("rerun")
    rerun.add_argument("--task-id", default="")
    rerun.add_argument("--task-guid", default="")
    rerun.add_argument("--run-id", default="")
    rerun.add_argument("--backend", default="")
    rerun.add_argument("--agent", default="")
    rerun.add_argument("--timeout", type=int, default=0)
    rerun.add_argument("--thinking", default="")
    rerun.add_argument("--session-key", default="")
    rerun.set_defaults(func=handlers["rerun"])

    create = sub.add_parser("create")
    create.add_argument("--summary", required=True)
    create.add_argument("--request", default="")
    create.add_argument("--repo-root", default="")
    create.add_argument("--kind", default="")
    create.add_argument("--tasklist-name", default="")
    create.add_argument("--force-new", action="store_true", default=False)
    create.set_defaults(func=handlers["create"])

    get = sub.add_parser("get")
    get.add_argument("--task-id", default="")
    get.add_argument("--task-guid", default="")
    get.add_argument("--include-completed", action="store_true", default=False)
    get.set_defaults(func=handlers["get"])

    comment = sub.add_parser("comment")
    comment.add_argument("--task-id", default="")
    comment.add_argument("--task-guid", default="")
    comment.add_argument("--include-completed", action="store_true", default=False)
    comment.add_argument("--content", required=True)
    comment.set_defaults(func=handlers["comment"])

    complete = sub.add_parser("complete")
    complete.add_argument("--task-id", default="")
    complete.add_argument("--task-guid", default="")
    complete.add_argument("--include-completed", action="store_true", default=False)
    complete.add_argument("--content", default="")
    complete.add_argument("--content-file", default="")
    complete.add_argument("--file", action="append", default=[])
    complete.add_argument("--commit-url", default="")
    complete.add_argument("--skip-head-commit-url", action="store_true", default=False)
    complete.add_argument("--force-review-bypass", action="store_true", default=False)
    complete.add_argument("--repo-root", default="")
    complete.set_defaults(func=handlers["complete"])

    update_description = sub.add_parser("update-description")
    update_description.add_argument("--task-id", default="")
    update_description.add_argument("--task-guid", default="")
    update_description.add_argument("--include-completed", action="store_true", default=False)
    update_description.add_argument("--mode", choices=("replace", "append"), default="replace")
    update_description.add_argument("--separator", default="\n\n")
    update_description.add_argument("--content", default="")
    update_description.add_argument("--content-file", default="")
    update_description.set_defaults(func=handlers["update_description"])

    listing = sub.add_parser("list")
    listing.add_argument("--limit", type=int, default=20)
    listing.add_argument("--asc", action="store_true", default=False)
    listing.add_argument("--include-completed", action="store_true", default=False)
    listing.set_defaults(func=handlers["list"])

    normalize_titles = sub.add_parser("normalize-titles")
    normalize_titles.add_argument("--include-completed", action="store_true", default=False)
    normalize_titles.set_defaults(func=handlers["normalize_titles"])

    search = sub.add_parser("search")
    search.add_argument("--query", required=True)
    search.add_argument("--limit", type=int, default=20)
    search.add_argument("--include-completed", action="store_true", default=False)
    search.set_defaults(func=handlers["search"])

    attachments = sub.add_parser("attachments")
    attachments.add_argument("--task-id", default="")
    attachments.add_argument("--task-guid", default="")
    attachments.add_argument("--include-completed", action="store_true", default=False)
    attachments.add_argument("--download-dir", default="")
    attachments.set_defaults(func=handlers["attachments"])

    upload_attachments = sub.add_parser("upload-attachments")
    upload_attachments.add_argument("--task-id", default="")
    upload_attachments.add_argument("--task-guid", default="")
    upload_attachments.add_argument("--include-completed", action="store_true", default=False)
    upload_attachments.add_argument("--file", action="append", default=[])
    upload_attachments.set_defaults(func=handlers["upload_attachments"])
    return parser
